-- pretty much the same (CLOB)
SELECT SS.SID,SS.USERNAME USERNAME,SS.OSUSER "USER", 
  to_char(ss.SQL_EXEC_START,'YYY/MM/DD HH24:MI:SS') start_time,
  AR.MODULE || ' @ ' || SS.machine CLIENT,
  SS.PROCESS PID,TO_CHAR(AR.LAST_LOAD_TIME, 'DD-Mon HH24:MM:SS') LOAD_TIME,
  AR.BUFFER_GETS BUFFER_GETS,
  W.EVENT EVENT,SS.status,AR.SQL_fullTEXT SQL
FROM V$SESSION_WAIT W,V$SQLAREA AR,V$SESSION SS, v$timer T
WHERE SS.SQL_ADDRESS = AR.ADDRESS
  AND SS.SQL_HASH_VALUE = AR.HASH_VALUE
  AND SS.SID = w.SID (+)
  AND ss.STATUS = 'ACTIVE'
  AND W.EVENT != 'client message'
  and upper(SS.USERNAME) like 'SYS%'
ORDER BY 4 desc

